// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/product/v1/product.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_ListProductsBySellerId_FullMethodName = "/product.v1.ProductService/ListProductsBySellerId"
	ProductService_ListMerchantProducts_FullMethodName   = "/product.v1.ProductService/ListMerchantProducts"
	ProductService_UpsertProduct_FullMethodName          = "/product.v1.ProductService/UpsertProduct"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// api for both merchants and customers.
type ProductServiceClient interface {
	// list products by seller_id, generally used by customers.
	ListProductsBySellerId(ctx context.Context, in *ListProductsBySellerIdRequest, opts ...grpc.CallOption) (*ListProductsBySellerIdResponse, error)
	// list all the products of the merchant.
	ListMerchantProducts(ctx context.Context, in *ListMerchantProductsRequest, opts ...grpc.CallOption) (*ListMerchantProductsResponse, error)
	// insert or update a product's details.
	UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*UpsertProductResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) ListProductsBySellerId(ctx context.Context, in *ListProductsBySellerIdRequest, opts ...grpc.CallOption) (*ListProductsBySellerIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsBySellerIdResponse)
	err := c.cc.Invoke(ctx, ProductService_ListProductsBySellerId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListMerchantProducts(ctx context.Context, in *ListMerchantProductsRequest, opts ...grpc.CallOption) (*ListMerchantProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantProductsResponse)
	err := c.cc.Invoke(ctx, ProductService_ListMerchantProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpsertProduct(ctx context.Context, in *UpsertProductRequest, opts ...grpc.CallOption) (*UpsertProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertProductResponse)
	err := c.cc.Invoke(ctx, ProductService_UpsertProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
//
// api for both merchants and customers.
type ProductServiceServer interface {
	// list products by seller_id, generally used by customers.
	ListProductsBySellerId(context.Context, *ListProductsBySellerIdRequest) (*ListProductsBySellerIdResponse, error)
	// list all the products of the merchant.
	ListMerchantProducts(context.Context, *ListMerchantProductsRequest) (*ListMerchantProductsResponse, error)
	// insert or update a product's details.
	UpsertProduct(context.Context, *UpsertProductRequest) (*UpsertProductResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) ListProductsBySellerId(context.Context, *ListProductsBySellerIdRequest) (*ListProductsBySellerIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductsBySellerId not implemented")
}
func (UnimplementedProductServiceServer) ListMerchantProducts(context.Context, *ListMerchantProductsRequest) (*ListMerchantProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMerchantProducts not implemented")
}
func (UnimplementedProductServiceServer) UpsertProduct(context.Context, *UpsertProductRequest) (*UpsertProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertProduct not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_ListProductsBySellerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsBySellerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProductsBySellerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListProductsBySellerId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProductsBySellerId(ctx, req.(*ListProductsBySellerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListMerchantProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListMerchantProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ListMerchantProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListMerchantProducts(ctx, req.(*ListMerchantProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpsertProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpsertProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_UpsertProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpsertProduct(ctx, req.(*UpsertProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductsBySellerId",
			Handler:    _ProductService_ListProductsBySellerId_Handler,
		},
		{
			MethodName: "ListMerchantProducts",
			Handler:    _ProductService_ListMerchantProducts_Handler,
		},
		{
			MethodName: "UpsertProduct",
			Handler:    _ProductService_UpsertProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/product/v1/product.proto",
}
