// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"azushop/internal/biz"
	"azushop/internal/conf"
	"azushop/internal/data"
	"azushop/internal/runner"
	"azushop/internal/server"
	"azushop/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireOrderApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	postgres, err := data.NewPostgres(confData)
	if err != nil {
		return nil, nil, err
	}
	orderRepo := data.NewOrderRepo(postgres)
	orderSubscriber, err := data.NewOrderSubscriber(confData)
	if err != nil {
		return nil, nil, err
	}
	kafkaProducer, err := data.NewKafkaProducer(confData)
	if err != nil {
		return nil, nil, err
	}
	orderPublisher := data.NewOrderPublisher(kafkaProducer)
	transaction := data.NewTransaction(postgres)
	orderUsecase := biz.NewOrderUsecase(orderRepo, orderSubscriber, orderPublisher, transaction)
	orderServiceClient, err := service.NewOrderServiceClient(confData)
	if err != nil {
		return nil, nil, err
	}
	orderService := service.NewOrderService(orderUsecase, orderServiceClient)
	grpcServer := server.NewOrderGRPCServer(confServer, orderService, logger)
	orderRunner := runner.NewOrderRunner(orderUsecase)
	app := newApp(logger, grpcServer, orderRunner)
	return app, func() {
	}, nil
}
