// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/pkg/telemetry"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(cd *conf.Data, cs *conf.Server) (*App, func(), error) {
	postgres, err := data.NewPostgres(cd)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(postgres)
	transaction := data.NewTransaction(postgres)
	inventorySubscriber, err := data.NewInventorySubscriber(cd)
	if err != nil {
		return nil, nil, err
	}
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, transaction, inventorySubscriber)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	inventoryServiceConnectHandler := service.NewInventoryServiceConnectHandler(inventoryService)
	textMapPropagator := telemetry.NewTextMapPropagator()
	connectServerConfig, err := newConnectServerConfig(inventoryServiceConnectHandler, cs, cd, textMapPropagator)
	if err != nil {
		return nil, nil, err
	}
	connectServer := server.NewConnectServer(connectServerConfig)
	metricsServer := server.NewMetricsServer(cs)
	inventoryRunner := server.NewInventoryRunner(inventoryUsecase)
	app := newApp(connectServer, metricsServer, inventoryRunner)
	return app, func() {
	}, nil
}

// wire.go:

var wireProviders = wire.NewSet(telemetry.NewTextMapPropagator, data.InventoryDataProviderSet, biz.NewInventoryUsecase, service.NewInventoryService, service.NewInventoryServiceConnectHandler, server.NewInventoryRunner, newConnectServerConfig, server.NewConnectServer, server.NewMetricsServer, newApp)
