// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/runner"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireInventoryApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	postgres, err := data.NewPostgres(confData)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(postgres)
	transaction := data.NewTransaction(postgres)
	inventorySubscriber, err := data.NewInventorySubscriber(confData)
	if err != nil {
		return nil, nil, err
	}
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, transaction, inventorySubscriber)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	tracerProvider, cleanup, err := server.NewGlobalTraceProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	grpcServer := server.NewInventoryGRPCServer(confServer, inventoryService, tracerProvider, logger)
	httpServer := server.NewInventoryHTTPServer(confServer, inventoryService, logger)
	inventoryRunner := runner.NewInventoryRunner(inventoryUsecase)
	app := newApp(logger, grpcServer, httpServer, inventoryRunner)
	return app, func() {
		cleanup()
	}, nil
}
