// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"azushop/internal/biz"
	"azushop/internal/conf"
	"azushop/internal/data"
	"azushop/internal/runner"
	"azushop/internal/server"
	"azushop/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func wireInventoryApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	inventoryRepo := data.NewInventoryRepo(dataData)
	transaction := data.NewTransaction(dataData)
	inventorySubscriber := data.NewInventorySubscriber(dataData)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, transaction, inventorySubscriber)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	grpcServer := server.NewInventoryGRPCServer(confServer, inventoryService, dataData, logger)
	inventoryRunner := runner.NewInventoryRunner(inventoryUsecase)
	app := newApp(logger, grpcServer, inventoryRunner)
	return app, func() {
		cleanup()
	}, nil
}
