apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
{{ .Files.Get .Values.gateway.config.file | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.service.name }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.gateway.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.service.name }}
    spec:
      containers:
        - name: envoy
          image: {{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}
          args: ["-c", "{{ .Values.gateway.config.mountPath }}/envoy.yaml"]
          ports:
            - containerPort: {{ .Values.gateway.service.targetPort }}
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.gateway.config.mountPath }}
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.service.name }}
spec:
  selector:
    app: {{ .Values.gateway.service.name }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      name: http
