apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
{{ .Files.Get "configs/infra/envoy.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.38.0
          args: ["-c", "/etc/envoy/envoy.yaml"]
          ports:
            - containerPort: 10000
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/envoy
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
    - port: 10000
      targetPort: 10000
      name: http
