apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaui
spec:
  selector:
    matchLabels:
      app: kafkaui
  template:
    metadata:
      labels:
        app: kafkaui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaui.image.repository }}:{{ .Values.kafkaui.image.tag }}
          ports:
            - containerPort: {{ .Values.kafkaui.service.targetPort }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Values.kafkaui.cluster.name | quote }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaui.cluster.bootstrapServers | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafkaui
spec:
  selector:
    app: kafkaui
  ports:
    - port: {{ .Values.kafkaui.service.port }}
      targetPort: {{ .Values.kafkaui.service.targetPort }}
