apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: {{ .Values.kafka.service.name }}
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}
          env:
            - name: KAFKA_NODE_ID
              value: "{{ .Values.kafka.nodeID }}"
            - name: KAFKA_PROCESS_ROLES
              value: {{ .Values.kafka.processRoles | quote }}
            - name: KAFKA_LISTENERS
              value: {{ .Values.kafka.listeners | quote }}
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ .Values.kafka.advertisedListeners | quote }}
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: {{ .Values.kafka.controllerListenerNames | quote }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.listenerSecurityProtocolMap | quote }}
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "{{ .Values.kafka.nodeID }}@{{ .Values.kafka.service.name }}:{{ .Values.kafka.service.controllerPort }}"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "{{ .Values.kafka.offsetsTopicReplicationFactor }}"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "{{ .Values.kafka.transactionStateLogReplicationFactor }}"
            - name: KAFKA_LOG_DIRS
              value: {{ .Values.kafka.logDirs | quote }}
            - name: CLUSTER_ID
              value: {{ .Values.kafka.clusterID | quote }}
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
          volumeMounts:
            - name: kafka-data
              mountPath: {{ .Values.kafka.persistence.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: {{ toYaml .Values.kafka.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
spec:
  selector:
    app: kafka
  ports:
    - name: default
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.port }}
    - name: controller
      port: {{ .Values.kafka.service.controllerPort }}
      targetPort: {{ .Values.kafka.service.controllerPort }}
