apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
{{ .Files.Get "configs/infra/loki.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  serviceName: {{ .Values.loki.service.name | quote }}
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: {{ .Values.loki.securityContext.fsGroup }}
        runAsUser: {{ .Values.loki.securityContext.runAsUser }}
        runAsGroup: {{ .Values.loki.securityContext.runAsGroup }}
      containers:
        - name: loki
          image: {{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}
          args: ["-config.file=/etc/loki/config/loki.yaml"]
          ports:
            - containerPort: {{ .Values.loki.service.targetPort }}
              name: http
          volumeMounts:
            - name: loki-data
              mountPath: {{ .Values.loki.persistence.mountPath }}
            - name: config-volume
              mountPath: /etc/loki/config
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        accessModes: {{ toYaml .Values.loki.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.loki.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loki.service.name }}
spec:
  selector:
    app: loki
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: {{ .Values.loki.service.targetPort }}
      name: http
