apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yml: |
{{ .Files.Get "configs/infra/otel-collector.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args: ["--config=/etc/otelcol/config.yml"]
          ports:
            - containerPort: {{ .Values.otelCollector.service.otlpGrpcPort }}
              name: otlp-grpc
            - containerPort: {{ .Values.otelCollector.service.otlpHttpPort }}
              name: otlp-http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - port: {{ .Values.otelCollector.service.otlpGrpcPort }}
      targetPort: {{ .Values.otelCollector.service.otlpGrpcPort }}
      name: otlp-grpc
    - port: {{ .Values.otelCollector.service.otlpHttpPort }}
      targetPort: {{ .Values.otelCollector.service.otlpHttpPort }}
      name: otlp-http
