apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.service.name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "{{ .Values.postgres.hookWeight }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgres.service.name }}
  serviceName: {{ .Values.postgres.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.service.name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
          ports:
            - containerPort: {{ .Values.postgres.service.targetPort }}
              name: postgres
          volumeMounts:
            - name: pg-data
              mountPath: {{ .Values.postgres.persistence.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: {{ toYaml .Values.postgres.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "{{ .Values.postgres.hookWeight }}"
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ .Values.postgres.service.name }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
