apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redis.replicas | default 1 }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: {{ .Values.redis.terminationGracePeriodSeconds }}
      containers:
        - name: redis
          image: redis:8.8.0-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: {{ .Values.redis.minCPU | quote }}
              memory: {{ .Values.redis.minMem | quote }}
            limits:
              cpu: {{ .Values.redis.maxCPU | quote }}
              memory: {{ .Values.redis.maxMem | quote }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
