apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: {{ .Values.redis.terminationGracePeriodSeconds }}
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          ports:
            - containerPort: {{ .Values.redis.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.redis.minCPU | quote }}
              memory: {{ .Values.redis.minMem | quote }}
            limits:
              cpu: {{ .Values.redis.maxCPU | quote }}
              memory: {{ .Values.redis.maxMem | quote }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
