apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
{{ .Files.Get "configs/infra/tempo.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  serviceName: "tempo-service"
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/etc/tempo/config/tempo.yaml"]
          ports:
            - containerPort: 3200
              name: http
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: tempo-data
              mountPath: /var/tempo
            - name: config-volume
              mountPath: /etc/tempo/config
      volumes:
        - name: config-volume
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: tempo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: http
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
