apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
{{ .Files.Get "configs/infra/tempo.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  serviceName: {{ .Values.tempo.service.name | quote }}
  replicas: {{ .Values.tempo.replicas }}
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: {{ .Values.tempo.image.repository }}:{{ .Values.tempo.image.tag }}
          args: ["-config.file=/etc/tempo/config/tempo.yaml"]
          ports:
            - containerPort: {{ .Values.tempo.service.httpPort }}
              name: http
            - containerPort: {{ .Values.tempo.service.otlpGrpcPort }}
              name: otlp-grpc
            - containerPort: {{ .Values.tempo.service.otlpHttpPort }}
              name: otlp-http
          volumeMounts:
            - name: tempo-data
              mountPath: {{ .Values.tempo.persistence.mountPath }}
            - name: config-volume
              mountPath: /etc/tempo/config
      volumes:
        - name: config-volume
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: tempo-data
      spec:
        accessModes: {{ toYaml .Values.tempo.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.tempo.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tempo.service.name }}
spec:
  selector:
    app: tempo
  ports:
    - port: {{ .Values.tempo.service.httpPort }}
      targetPort: {{ .Values.tempo.service.httpPort }}
      name: http
    - port: {{ .Values.tempo.service.otlpGrpcPort }}
      targetPort: {{ .Values.tempo.service.otlpGrpcPort }}
      name: otlp-grpc
    - port: {{ .Values.tempo.service.otlpHttpPort }}
      targetPort: {{ .Values.tempo.service.otlpHttpPort }}
      name: otlp-http
