// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/product/v1/product.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED ProductStatus = 0
	ProductStatus_PRODUCT_STATUS_DRAFT       ProductStatus = 1
	ProductStatus_PRODUCT_STATUS_PENDING     ProductStatus = 2
	ProductStatus_PRODUCT_STATUS_ACTIVE      ProductStatus = 3
	ProductStatus_PRODUCT_STATUS_OFFLINE     ProductStatus = 4
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "PRODUCT_STATUS_DRAFT",
		2: "PRODUCT_STATUS_PENDING",
		3: "PRODUCT_STATUS_ACTIVE",
		4: "PRODUCT_STATUS_OFFLINE",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED": 0,
		"PRODUCT_STATUS_DRAFT":       1,
		"PRODUCT_STATUS_PENDING":     2,
		"PRODUCT_STATUS_ACTIVE":      3,
		"PRODUCT_STATUS_OFFLINE":     4,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_product_v1_product_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_api_product_v1_product_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *SearchProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Sku struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO(3): optional when used as input
	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attrs         *structpb.Struct `protobuf:"bytes,2,opt,name=attrs,proto3" json:"attrs,omitempty"`
	UnitPrice     string           `protobuf:"bytes,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sku) Reset() {
	*x = Sku{}
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *Sku) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sku) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Sku) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO(3): optional when used as input
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// TODO(3): optional when used as input
	SellerId      int32         `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Description   string        `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Skus          []*Sku        `protobuf:"bytes,5,rep,name=skus,proto3" json:"skus,omitempty"`
	ProductStatus ProductStatus `protobuf:"varint,6,opt,name=product_status,json=productStatus,proto3,enum=product.v1.ProductStatus" json:"product_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Product) GetSellerId() int32 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSkus() []*Sku {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *Product) GetProductStatus() ProductStatus {
	if x != nil {
		return x.ProductStatus
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

type ListSellerProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// use 0 for the first request.
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// max 100
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SellerId int32 `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	// filter by product status.
	ProductStatus *ProductStatus `protobuf:"varint,4,opt,name=product_status,json=productStatus,proto3,enum=product.v1.ProductStatus,oneof" json:"product_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSellerProductsRequest) Reset() {
	*x = ListSellerProductsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSellerProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSellerProductsRequest) ProtoMessage() {}

func (x *ListSellerProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSellerProductsRequest.ProtoReflect.Descriptor instead.
func (*ListSellerProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListSellerProductsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSellerProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSellerProductsRequest) GetSellerId() int32 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ListSellerProductsRequest) GetProductStatus() ProductStatus {
	if x != nil && x.ProductStatus != nil {
		return *x.ProductStatus
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

type ListSellerProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSellerProductsResponse) Reset() {
	*x = ListSellerProductsResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSellerProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSellerProductsResponse) ProtoMessage() {}

func (x *ListSellerProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSellerProductsResponse.ProtoReflect.Descriptor instead.
func (*ListSellerProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListSellerProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type BatchCreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateProductRequest) Reset() {
	*x = BatchCreateProductRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateProductRequest) ProtoMessage() {}

func (x *BatchCreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateProductRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCreateProductRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type BatchCreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateProductResponse) Reset() {
	*x = BatchCreateProductResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateProductResponse) ProtoMessage() {}

func (x *BatchCreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateProductResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateProductResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{7}
}

type BatchUpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateProductRequest) Reset() {
	*x = BatchUpdateProductRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateProductRequest) ProtoMessage() {}

func (x *BatchUpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateProductRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *BatchUpdateProductRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *BatchUpdateProductRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// TODO(2): update strategy and update results.
type BatchUpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateProductResponse) Reset() {
	*x = BatchUpdateProductResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateProductResponse) ProtoMessage() {}

func (x *BatchUpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateProductResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{9}
}

type BatchGetSkusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// use "" for the first request.
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// max 100
	PageSize      int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SkuIds        []string `protobuf:"bytes,3,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSkusRequest) Reset() {
	*x = BatchGetSkusRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSkusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSkusRequest) ProtoMessage() {}

func (x *BatchGetSkusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSkusRequest.ProtoReflect.Descriptor instead.
func (*BatchGetSkusRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetSkusRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *BatchGetSkusRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BatchGetSkusRequest) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type SkuDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *Sku                   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuDetail) Reset() {
	*x = SkuDetail{}
	mi := &file_api_product_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuDetail) ProtoMessage() {}

func (x *SkuDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuDetail.ProtoReflect.Descriptor instead.
func (*SkuDetail) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *SkuDetail) GetSku() *Sku {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *SkuDetail) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type BatchGetSkusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuDetails    []*SkuDetail           `protobuf:"bytes,1,rep,name=sku_details,json=skuDetails,proto3" json:"sku_details,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSkusResponse) Reset() {
	*x = BatchGetSkusResponse{}
	mi := &file_api_product_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSkusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSkusResponse) ProtoMessage() {}

func (x *BatchGetSkusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSkusResponse.ProtoReflect.Descriptor instead.
func (*BatchGetSkusResponse) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetSkusResponse) GetSkuDetails() []*SkuDetail {
	if x != nil {
		return x.SkuDetails
	}
	return nil
}

func (x *BatchGetSkusResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_product_v1_product_proto protoreflect.FileDescriptor

const file_api_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1capi/product/v1/product.proto\x12\n" +
	"product.v1\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\"m\n" +
	"\x15SearchProductsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"I\n" +
	"\x16SearchProductsResponse\x12/\n" +
	"\bproducts\x18\x03 \x03(\v2\x13.product.v1.ProductR\bproducts\"c\n" +
	"\x03Sku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x05attrs\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05attrs\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\tR\tunitPrice\"\xe2\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x05R\bsellerId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\x04skus\x18\x05 \x03(\v2\x0f.product.v1.SkuR\x04skus\x12@\n" +
	"\x0eproduct_status\x18\x06 \x01(\x0e2\x19.product.v1.ProductStatusR\rproductStatus\"\xce\x01\n" +
	"\x19ListSellerProductsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x05R\bsellerId\x12E\n" +
	"\x0eproduct_status\x18\x04 \x01(\x0e2\x19.product.v1.ProductStatusH\x00R\rproductStatus\x88\x01\x01B\x11\n" +
	"\x0f_product_status\"M\n" +
	"\x1aListSellerProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\"L\n" +
	"\x19BatchCreateProductRequest\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\"\x1c\n" +
	"\x1aBatchCreateProductResponse\"\x89\x01\n" +
	"\x19BatchUpdateProductRequest\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1c\n" +
	"\x1aBatchUpdateProductResponse\"j\n" +
	"\x13BatchGetSkusRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asku_ids\x18\x03 \x03(\tR\x06skuIds\"Q\n" +
	"\tSkuDetail\x12!\n" +
	"\x03sku\x18\x01 \x01(\v2\x0f.product.v1.SkuR\x03sku\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\"v\n" +
	"\x14BatchGetSkusResponse\x126\n" +
	"\vsku_details\x18\x01 \x03(\v2\x15.product.v1.SkuDetailR\n" +
	"skuDetails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x9c\x01\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PRODUCT_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16PRODUCT_STATUS_PENDING\x10\x02\x12\x19\n" +
	"\x15PRODUCT_STATUS_ACTIVE\x10\x03\x12\x1a\n" +
	"\x16PRODUCT_STATUS_OFFLINE\x10\x042\xeb\x03\n" +
	"\x0eProductService\x12W\n" +
	"\x0eSearchProducts\x12!.product.v1.SearchProductsRequest\x1a\".product.v1.SearchProductsResponse\x12c\n" +
	"\x12ListSellerProducts\x12%.product.v1.ListSellerProductsRequest\x1a&.product.v1.ListSellerProductsResponse\x12c\n" +
	"\x12BatchCreateProduct\x12%.product.v1.BatchCreateProductRequest\x1a&.product.v1.BatchCreateProductResponse\x12c\n" +
	"\x12BatchUpdateProduct\x12%.product.v1.BatchUpdateProductRequest\x1a&.product.v1.BatchUpdateProductResponse\x12Q\n" +
	"\fBatchGetSkus\x12\x1f.product.v1.BatchGetSkusRequest\x1a .product.v1.BatchGetSkusResponseB4Z2github.com/azusayn/azushop/proto/api/product/v1;v1b\x06proto3"

var (
	file_api_product_v1_product_proto_rawDescOnce sync.Once
	file_api_product_v1_product_proto_rawDescData []byte
)

func file_api_product_v1_product_proto_rawDescGZIP() []byte {
	file_api_product_v1_product_proto_rawDescOnce.Do(func() {
		file_api_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)))
	})
	return file_api_product_v1_product_proto_rawDescData
}

var file_api_product_v1_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_product_v1_product_proto_goTypes = []any{
	(ProductStatus)(0),                 // 0: product.v1.ProductStatus
	(*SearchProductsRequest)(nil),      // 1: product.v1.SearchProductsRequest
	(*SearchProductsResponse)(nil),     // 2: product.v1.SearchProductsResponse
	(*Sku)(nil),                        // 3: product.v1.Sku
	(*Product)(nil),                    // 4: product.v1.Product
	(*ListSellerProductsRequest)(nil),  // 5: product.v1.ListSellerProductsRequest
	(*ListSellerProductsResponse)(nil), // 6: product.v1.ListSellerProductsResponse
	(*BatchCreateProductRequest)(nil),  // 7: product.v1.BatchCreateProductRequest
	(*BatchCreateProductResponse)(nil), // 8: product.v1.BatchCreateProductResponse
	(*BatchUpdateProductRequest)(nil),  // 9: product.v1.BatchUpdateProductRequest
	(*BatchUpdateProductResponse)(nil), // 10: product.v1.BatchUpdateProductResponse
	(*BatchGetSkusRequest)(nil),        // 11: product.v1.BatchGetSkusRequest
	(*SkuDetail)(nil),                  // 12: product.v1.SkuDetail
	(*BatchGetSkusResponse)(nil),       // 13: product.v1.BatchGetSkusResponse
	(*structpb.Struct)(nil),            // 14: google.protobuf.Struct
	(*fieldmaskpb.FieldMask)(nil),      // 15: google.protobuf.FieldMask
}
var file_api_product_v1_product_proto_depIdxs = []int32{
	4,  // 0: product.v1.SearchProductsResponse.products:type_name -> product.v1.Product
	14, // 1: product.v1.Sku.attrs:type_name -> google.protobuf.Struct
	3,  // 2: product.v1.Product.skus:type_name -> product.v1.Sku
	0,  // 3: product.v1.Product.product_status:type_name -> product.v1.ProductStatus
	0,  // 4: product.v1.ListSellerProductsRequest.product_status:type_name -> product.v1.ProductStatus
	4,  // 5: product.v1.ListSellerProductsResponse.products:type_name -> product.v1.Product
	4,  // 6: product.v1.BatchCreateProductRequest.products:type_name -> product.v1.Product
	4,  // 7: product.v1.BatchUpdateProductRequest.products:type_name -> product.v1.Product
	15, // 8: product.v1.BatchUpdateProductRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 9: product.v1.SkuDetail.sku:type_name -> product.v1.Sku
	12, // 10: product.v1.BatchGetSkusResponse.sku_details:type_name -> product.v1.SkuDetail
	1,  // 11: product.v1.ProductService.SearchProducts:input_type -> product.v1.SearchProductsRequest
	5,  // 12: product.v1.ProductService.ListSellerProducts:input_type -> product.v1.ListSellerProductsRequest
	7,  // 13: product.v1.ProductService.BatchCreateProduct:input_type -> product.v1.BatchCreateProductRequest
	9,  // 14: product.v1.ProductService.BatchUpdateProduct:input_type -> product.v1.BatchUpdateProductRequest
	11, // 15: product.v1.ProductService.BatchGetSkus:input_type -> product.v1.BatchGetSkusRequest
	2,  // 16: product.v1.ProductService.SearchProducts:output_type -> product.v1.SearchProductsResponse
	6,  // 17: product.v1.ProductService.ListSellerProducts:output_type -> product.v1.ListSellerProductsResponse
	8,  // 18: product.v1.ProductService.BatchCreateProduct:output_type -> product.v1.BatchCreateProductResponse
	10, // 19: product.v1.ProductService.BatchUpdateProduct:output_type -> product.v1.BatchUpdateProductResponse
	13, // 20: product.v1.ProductService.BatchGetSkus:output_type -> product.v1.BatchGetSkusResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_product_v1_product_proto_init() }
func file_api_product_v1_product_proto_init() {
	if File_api_product_v1_product_proto != nil {
		return
	}
	file_api_product_v1_product_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_v1_product_proto_goTypes,
		DependencyIndexes: file_api_product_v1_product_proto_depIdxs,
		EnumInfos:         file_api_product_v1_product_proto_enumTypes,
		MessageInfos:      file_api_product_v1_product_proto_msgTypes,
	}.Build()
	File_api_product_v1_product_proto = out.File
	file_api_product_v1_product_proto_goTypes = nil
	file_api_product_v1_product_proto_depIdxs = nil
}
