// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.5
// source: api/inventory/v1/inventory.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInventoryServiceAdminListSKUs = "/inventory.v1.InventoryService/AdminListSKUs"
const OperationInventoryServiceCreateSKU = "/inventory.v1.InventoryService/CreateSKU"
const OperationInventoryServiceListSKUs = "/inventory.v1.InventoryService/ListSKUs"
const OperationInventoryServiceUpdateSKU = "/inventory.v1.InventoryService/UpdateSKU"

type InventoryServiceHTTPServer interface {
	// AdminListSKUs list skus by product id with full details(available, stock, reserved stocks).
	AdminListSKUs(context.Context, *AdminListSKUsRequest) (*AdminListSKUsResponse, error)
	// CreateSKU SKU management.
	CreateSKU(context.Context, *CreateSKURequest) (*CreateSKUResponse, error)
	// ListSKUs list skus by product id.
	ListSKUs(context.Context, *ListSKUsRequest) (*ListSKUsResponse, error)
	// UpdateSKU update sku with sku details.
	UpdateSKU(context.Context, *UpdateSKURequest) (*UpdateSKUResponse, error)
}

func RegisterInventoryServiceHTTPServer(s *http.Server, srv InventoryServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/products/{product_id}/skus", _InventoryService_CreateSKU0_HTTP_Handler(srv))
	r.PUT("/v1/skus", _InventoryService_UpdateSKU0_HTTP_Handler(srv))
	r.GET("/v1/products/{product_id}/skus", _InventoryService_ListSKUs0_HTTP_Handler(srv))
	r.GET("/v1/admin/products/{product_id}/skus", _InventoryService_AdminListSKUs0_HTTP_Handler(srv))
}

func _InventoryService_CreateSKU0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSKURequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceCreateSKU)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSKU(ctx, req.(*CreateSKURequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSKUResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryService_UpdateSKU0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSKURequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceUpdateSKU)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSKU(ctx, req.(*UpdateSKURequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSKUResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryService_ListSKUs0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSKUsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceListSKUs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSKUs(ctx, req.(*ListSKUsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSKUsResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryService_AdminListSKUs0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListSKUsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceAdminListSKUs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListSKUs(ctx, req.(*AdminListSKUsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListSKUsResponse)
		return ctx.Result(200, reply)
	}
}

type InventoryServiceHTTPClient interface {
	// AdminListSKUs list skus by product id with full details(available, stock, reserved stocks).
	AdminListSKUs(ctx context.Context, req *AdminListSKUsRequest, opts ...http.CallOption) (rsp *AdminListSKUsResponse, err error)
	// CreateSKU SKU management.
	CreateSKU(ctx context.Context, req *CreateSKURequest, opts ...http.CallOption) (rsp *CreateSKUResponse, err error)
	// ListSKUs list skus by product id.
	ListSKUs(ctx context.Context, req *ListSKUsRequest, opts ...http.CallOption) (rsp *ListSKUsResponse, err error)
	// UpdateSKU update sku with sku details.
	UpdateSKU(ctx context.Context, req *UpdateSKURequest, opts ...http.CallOption) (rsp *UpdateSKUResponse, err error)
}

type InventoryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInventoryServiceHTTPClient(client *http.Client) InventoryServiceHTTPClient {
	return &InventoryServiceHTTPClientImpl{client}
}

// AdminListSKUs list skus by product id with full details(available, stock, reserved stocks).
func (c *InventoryServiceHTTPClientImpl) AdminListSKUs(ctx context.Context, in *AdminListSKUsRequest, opts ...http.CallOption) (*AdminListSKUsResponse, error) {
	var out AdminListSKUsResponse
	pattern := "/v1/admin/products/{product_id}/skus"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInventoryServiceAdminListSKUs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSKU SKU management.
func (c *InventoryServiceHTTPClientImpl) CreateSKU(ctx context.Context, in *CreateSKURequest, opts ...http.CallOption) (*CreateSKUResponse, error) {
	var out CreateSKUResponse
	pattern := "/v1/products/{product_id}/skus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryServiceCreateSKU))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSKUs list skus by product id.
func (c *InventoryServiceHTTPClientImpl) ListSKUs(ctx context.Context, in *ListSKUsRequest, opts ...http.CallOption) (*ListSKUsResponse, error) {
	var out ListSKUsResponse
	pattern := "/v1/products/{product_id}/skus"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInventoryServiceListSKUs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSKU update sku with sku details.
func (c *InventoryServiceHTTPClientImpl) UpdateSKU(ctx context.Context, in *UpdateSKURequest, opts ...http.CallOption) (*UpdateSKUResponse, error) {
	var out UpdateSKUResponse
	pattern := "/v1/skus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryServiceUpdateSKU))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
