// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInventoryServiceAdjustStock = "/inventory.v1.InventoryService/AdjustStock"
const OperationInventoryServiceBatchGetStock = "/inventory.v1.InventoryService/BatchGetStock"
const OperationInventoryServiceReleaseStock = "/inventory.v1.InventoryService/ReleaseStock"

type InventoryServiceHTTPServer interface {
	// AdjustStock interfaces used by merchants and administrators.
	// sets stock to a specific quantity.
	AdjustStock(context.Context, *AdjustStockRequest) (*AdjustStockResponse, error)
	// BatchGetStock retrieves SKU information for given SKU IDs.
	BatchGetStock(context.Context, *BatchGetStockRequest) (*BatchGetStockResponse, error)
	// ReleaseStock interfaces used by internal services.
	// release reserved stock when a customer cancels an order.
	// TODO(3): remove it and use message queue.
	ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error)
}

func RegisterInventoryServiceHTTPServer(s *http.Server, srv InventoryServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/inventory/stock/adjust", _InventoryService_AdjustStock0_HTTP_Handler(srv))
	r.POST("/v1/inventory/stock/batch", _InventoryService_BatchGetStock0_HTTP_Handler(srv))
	r.POST("/v1/inventory/stock/release", _InventoryService_ReleaseStock0_HTTP_Handler(srv))
}

func _InventoryService_AdjustStock0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdjustStockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceAdjustStock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdjustStock(ctx, req.(*AdjustStockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdjustStockResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryService_BatchGetStock0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchGetStockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceBatchGetStock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchGetStock(ctx, req.(*BatchGetStockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchGetStockResponse)
		return ctx.Result(200, reply)
	}
}

func _InventoryService_ReleaseStock0_HTTP_Handler(srv InventoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReleaseStockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInventoryServiceReleaseStock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReleaseStock(ctx, req.(*ReleaseStockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReleaseStockResponse)
		return ctx.Result(200, reply)
	}
}

type InventoryServiceHTTPClient interface {
	// AdjustStock interfaces used by merchants and administrators.
	// sets stock to a specific quantity.
	AdjustStock(ctx context.Context, req *AdjustStockRequest, opts ...http.CallOption) (rsp *AdjustStockResponse, err error)
	// BatchGetStock retrieves SKU information for given SKU IDs.
	BatchGetStock(ctx context.Context, req *BatchGetStockRequest, opts ...http.CallOption) (rsp *BatchGetStockResponse, err error)
	// ReleaseStock interfaces used by internal services.
	// release reserved stock when a customer cancels an order.
	// TODO(3): remove it and use message queue.
	ReleaseStock(ctx context.Context, req *ReleaseStockRequest, opts ...http.CallOption) (rsp *ReleaseStockResponse, err error)
}

type InventoryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInventoryServiceHTTPClient(client *http.Client) InventoryServiceHTTPClient {
	return &InventoryServiceHTTPClientImpl{client}
}

// AdjustStock interfaces used by merchants and administrators.
// sets stock to a specific quantity.
func (c *InventoryServiceHTTPClientImpl) AdjustStock(ctx context.Context, in *AdjustStockRequest, opts ...http.CallOption) (*AdjustStockResponse, error) {
	var out AdjustStockResponse
	pattern := "/v1/inventory/stock/adjust"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryServiceAdjustStock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// BatchGetStock retrieves SKU information for given SKU IDs.
func (c *InventoryServiceHTTPClientImpl) BatchGetStock(ctx context.Context, in *BatchGetStockRequest, opts ...http.CallOption) (*BatchGetStockResponse, error) {
	var out BatchGetStockResponse
	pattern := "/v1/inventory/stock/batch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryServiceBatchGetStock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReleaseStock interfaces used by internal services.
// release reserved stock when a customer cancels an order.
// TODO(3): remove it and use message queue.
func (c *InventoryServiceHTTPClientImpl) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...http.CallOption) (*ReleaseStockResponse, error) {
	var out ReleaseStockResponse
	pattern := "/v1/inventory/stock/release"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInventoryServiceReleaseStock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
