// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/inventory/v1/inventory.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateSKU_FullMethodName     = "/inventory.v1.InventoryService/CreateSKU"
	InventoryService_UpdateSKU_FullMethodName     = "/inventory.v1.InventoryService/UpdateSKU"
	InventoryService_ListSKUs_FullMethodName      = "/inventory.v1.InventoryService/ListSKUs"
	InventoryService_AdminListSKUs_FullMethodName = "/inventory.v1.InventoryService/AdminListSKUs"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service for managing SKUs.
type InventoryServiceClient interface {
	// SKU management.
	CreateSKU(ctx context.Context, in *CreateSKURequest, opts ...grpc.CallOption) (*CreateSKUResponse, error)
	// update sku with sku details.
	UpdateSKU(ctx context.Context, in *UpdateSKURequest, opts ...grpc.CallOption) (*UpdateSKUResponse, error)
	// list skus by product id.
	ListSKUs(ctx context.Context, in *ListSKUsRequest, opts ...grpc.CallOption) (*ListSKUsResponse, error)
	// list skus by product id with full details(available, stock, reserved stocks).
	AdminListSKUs(ctx context.Context, in *AdminListSKUsRequest, opts ...grpc.CallOption) (*AdminListSKUsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateSKU(ctx context.Context, in *CreateSKURequest, opts ...grpc.CallOption) (*CreateSKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSKUResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateSKU(ctx context.Context, in *UpdateSKURequest, opts ...grpc.CallOption) (*UpdateSKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSKUResponse)
	err := c.cc.Invoke(ctx, InventoryService_UpdateSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListSKUs(ctx context.Context, in *ListSKUsRequest, opts ...grpc.CallOption) (*ListSKUsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSKUsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListSKUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) AdminListSKUs(ctx context.Context, in *AdminListSKUsRequest, opts ...grpc.CallOption) (*AdminListSKUsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListSKUsResponse)
	err := c.cc.Invoke(ctx, InventoryService_AdminListSKUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// service for managing SKUs.
type InventoryServiceServer interface {
	// SKU management.
	CreateSKU(context.Context, *CreateSKURequest) (*CreateSKUResponse, error)
	// update sku with sku details.
	UpdateSKU(context.Context, *UpdateSKURequest) (*UpdateSKUResponse, error)
	// list skus by product id.
	ListSKUs(context.Context, *ListSKUsRequest) (*ListSKUsResponse, error)
	// list skus by product id with full details(available, stock, reserved stocks).
	AdminListSKUs(context.Context, *AdminListSKUsRequest) (*AdminListSKUsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateSKU(context.Context, *CreateSKURequest) (*CreateSKUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSKU not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateSKU(context.Context, *UpdateSKURequest) (*UpdateSKUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSKU not implemented")
}
func (UnimplementedInventoryServiceServer) ListSKUs(context.Context, *ListSKUsRequest) (*ListSKUsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSKUs not implemented")
}
func (UnimplementedInventoryServiceServer) AdminListSKUs(context.Context, *AdminListSKUsRequest) (*AdminListSKUsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListSKUs not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateSKU(ctx, req.(*CreateSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateSKU(ctx, req.(*UpdateSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListSKUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSKUsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListSKUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListSKUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListSKUs(ctx, req.(*ListSKUsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_AdminListSKUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListSKUsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).AdminListSKUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_AdminListSKUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).AdminListSKUs(ctx, req.(*AdminListSKUsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSKU",
			Handler:    _InventoryService_CreateSKU_Handler,
		},
		{
			MethodName: "UpdateSKU",
			Handler:    _InventoryService_UpdateSKU_Handler,
		},
		{
			MethodName: "ListSKUs",
			Handler:    _InventoryService_ListSKUs_Handler,
		},
		{
			MethodName: "AdminListSKUs",
			Handler:    _InventoryService_AdminListSKUs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/inventory/v1/inventory.proto",
}
