// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"azushop/internal/biz"
	"azushop/internal/conf"
	"azushop/internal/data"
	"azushop/internal/server"
	"azushop/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

func wireProductApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData)
	productPublisher := data.NewProductPublisher(dataData)
	productUsecase := biz.NewProductUsecase(productRepo, productPublisher)
	productService := service.NewProductService(productUsecase)
	grpcServer := server.NewProductGRPCServer(confServer, productService, dataData, logger)
	app := newApp(logger, grpcServer, nil)
	return app, func() {
		cleanup()
	}, nil
}
