// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/pkg/llm"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(cd *conf.Data, cs *conf.Server) (*App, func(), error) {
	postgres, err := data.NewPostgres(cd)
	if err != nil {
		return nil, nil, err
	}
	redis, err := data.NewRedis(cd)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(postgres, redis)
	kafkaProducer, err := data.NewKafkaProducer(cd)
	if err != nil {
		return nil, nil, err
	}
	productPublisher := data.NewProductPublisher(kafkaProducer)
	openAIClient := llm.NewOpenAIClient(cd)
	productUsecase := biz.NewProductUsecase(productRepo, productPublisher, openAIClient)
	productService := service.NewProductService(productUsecase, cd)
	productServiceConnectHandler := service.NewProductServiceConnectHandler(productService)
	connectServerConfig, err := newConnectServerConfig(productServiceConnectHandler, cd, cs)
	if err != nil {
		return nil, nil, err
	}
	connectServer := server.NewConnectServer(connectServerConfig)
	metricsServer := server.NewMetricsServer(cs)
	app := newApp(connectServer, metricsServer)
	return app, func() {
	}, nil
}

// wire.go:

var wireProviders = wire.NewSet(data.ProductDataProviderSet, biz.NewProductUsecase, llm.NewOpenAIClient, service.NewProductService, service.NewProductServiceConnectHandler, newConnectServerConfig, server.NewConnectServer, server.NewMetricsServer, newApp)
