// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/pkg/llm"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireProductApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	postgres, err := data.NewPostgres(confData)
	if err != nil {
		return nil, nil, err
	}
	redis, err := data.NewRedis(confData)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(postgres, redis)
	kafkaProducer, err := data.NewKafkaProducer(confData)
	if err != nil {
		return nil, nil, err
	}
	productPublisher := data.NewProductPublisher(kafkaProducer)
	openAIClient := llm.NewOpenAIClient(confData)
	productUsecase := biz.NewProductUsecase(productRepo, productPublisher, openAIClient)
	productService := service.NewProductService(productUsecase, confData)
	tracerProvider, cleanup, err := server.NewGlobalTraceProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	grpcServer, err := server.NewProductGRPCServer(confServer, confData, productService, tracerProvider, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewProductHTTPServer(confServer, productService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
