// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(cd *conf.Data, cs *conf.Server) (*App, func(), error) {
	postgres, err := data.NewPostgres(cd)
	if err != nil {
		return nil, nil, err
	}
	redis, err := data.NewRedis(cd)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(postgres, redis)
	kafkaProducer, err := data.NewKafkaProducer(cd)
	if err != nil {
		return nil, nil, err
	}
	paymentPublisher := data.NewPaymentPublisher(kafkaProducer)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, paymentPublisher)
	orderServiceClient := data.NewOrderClient(cd)
	paymentService, err := service.NewPaymentService(paymentUsecase, orderServiceClient, cd)
	if err != nil {
		return nil, nil, err
	}
	paymentServiceConnectHandler := service.NewPaymentServiceConnectHandler(paymentService)
	paymentCallbackHandler := service.NewPaymentCallbackHandler(paymentUsecase)
	connectServerConfig, err := newConnectServerConfig(paymentServiceConnectHandler, paymentCallbackHandler, cs, cd)
	if err != nil {
		return nil, nil, err
	}
	connectServer := server.NewConnectServer(connectServerConfig)
	metricsServer := server.NewMetricsServer(cs)
	app := newApp(connectServer, metricsServer)
	return app, func() {
	}, nil
}

// wire.go:

var wireProviders = wire.NewSet(data.PaymentDataProviderSet, biz.NewPaymentUsecase, service.NewPaymentService, service.NewPaymentServiceConnectHandler, service.NewPaymentCallbackHandler, newConnectServerConfig, server.NewConnectServer, server.NewMetricsServer, newApp)
