// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wirePaymentApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	postgres, err := data.NewPostgres(confData)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(postgres)
	kafkaProducer, err := data.NewKafkaProducer(confData)
	if err != nil {
		return nil, nil, err
	}
	paymentPublisher := data.NewPaymentPublisher(kafkaProducer)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, paymentPublisher)
	paymentService, err := service.NewPaymentService(paymentUsecase, confData)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, cleanup, err := server.NewGlobalTraceProvider(confData)
	if err != nil {
		return nil, nil, err
	}
	grpcServer, err := server.NewPaymentGRPCServer(confServer, confData, paymentService, tracerProvider, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewPaymentHTTPServer(confServer, paymentService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
