// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(serverConfig *conf.Server, dataConfig *conf.Data) (*App, func(), error) {
	postgres, err := data.NewPostgres(dataConfig)
	if err != nil {
		return nil, nil, err
	}
	paymentRepo := data.NewPaymentRepo(postgres)
	kafkaProducer, err := data.NewKafkaProducer(dataConfig)
	if err != nil {
		return nil, nil, err
	}
	paymentPublisher := data.NewPaymentPublisher(kafkaProducer)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, paymentPublisher)
	paymentService, err := service.NewPaymentService(paymentUsecase, dataConfig)
	if err != nil {
		return nil, nil, err
	}
	paymentServiceConnectHandler := service.NewPaymentServiceConnectHandler(paymentService)
	app, err := newApp(serverConfig, dataConfig, paymentServiceConnectHandler)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
	}, nil
}

// wire.go:

var wireProviders = wire.NewSet(data.PaymentDataProviderSet, biz.NewPaymentUsecase, service.NewPaymentService, service.NewPaymentServiceConnectHandler, newApp)
