// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnectServerAddr string                 `protobuf:"bytes,1,opt,name=connect_server_addr,json=connectServerAddr,proto3" json:"connect_server_addr,omitempty"`
	MetricsServerAddr string                 `protobuf:"bytes,2,opt,name=metrics_server_addr,json=metricsServerAddr,proto3" json:"metrics_server_addr,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetConnectServerAddr() string {
	if x != nil {
		return x.ConnectServerAddr
	}
	return ""
}

func (x *Server) GetMetricsServerAddr() string {
	if x != nil {
		return x.MetricsServerAddr
	}
	return ""
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type ServiceAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Inventory     string                 `protobuf:"bytes,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Auth          string                 `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Payment       string                 `protobuf:"bytes,5,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAddr) Reset() {
	*x = ServiceAddr{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAddr) ProtoMessage() {}

func (x *ServiceAddr) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAddr.ProtoReflect.Descriptor instead.
func (*ServiceAddr) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceAddr) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ServiceAddr) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

func (x *ServiceAddr) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ServiceAddr) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *ServiceAddr) GetPayment() string {
	if x != nil {
		return x.Payment
	}
	return ""
}

type Payment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StripeSecretKey  string                 `protobuf:"bytes,1,opt,name=stripe_secret_key,json=stripeSecretKey,proto3" json:"stripe_secret_key,omitempty"`
	StripeSuccessUrl string                 `protobuf:"bytes,2,opt,name=stripe_success_url,json=stripeSuccessUrl,proto3" json:"stripe_success_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetStripeSecretKey() string {
	if x != nil {
		return x.StripeSecretKey
	}
	return ""
}

func (x *Payment) GetStripeSuccessUrl() string {
	if x != nil {
		return x.StripeSuccessUrl
	}
	return ""
}

type Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerAddrs   []string               `protobuf:"bytes,1,rep,name=broker_addrs,json=brokerAddrs,proto3" json:"broker_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Kafka) GetBrokerAddrs() []string {
	if x != nil {
		return x.BrokerAddrs
	}
	return nil
}

type EmbeddingAPI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxDistance   float32                `protobuf:"fixed32,4,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingAPI) Reset() {
	*x = EmbeddingAPI{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingAPI) ProtoMessage() {}

func (x *EmbeddingAPI) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingAPI.ProtoReflect.Descriptor instead.
func (*EmbeddingAPI) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *EmbeddingAPI) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *EmbeddingAPI) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *EmbeddingAPI) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingAPI) GetMaxDistance() float32 {
	if x != nil {
		return x.MaxDistance
	}
	return 0
}

type Data struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Database        *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis           *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	ServiceAddr     *ServiceAddr           `protobuf:"bytes,3,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	Payment         *Payment               `protobuf:"bytes,4,opt,name=payment,proto3" json:"payment,omitempty"`
	Kafka           *Kafka                 `protobuf:"bytes,5,opt,name=kafka,proto3" json:"kafka,omitempty"`
	AppName         string                 `protobuf:"bytes,6,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Auth            *Auth                  `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	OtlpGrpcAddress string                 `protobuf:"bytes,8,opt,name=otlp_grpc_address,json=otlpGrpcAddress,proto3" json:"otlp_grpc_address,omitempty"`
	EmbeddingApi    *EmbeddingAPI          `protobuf:"bytes,9,opt,name=embedding_api,json=embeddingApi,proto3" json:"embedding_api,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetServiceAddr() *ServiceAddr {
	if x != nil {
		return x.ServiceAddr
	}
	return nil
}

func (x *Data) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Data) GetKafka() *Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Data) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Data) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Data) GetOtlpGrpcAddress() string {
	if x != nil {
		return x.OtlpGrpcAddress
	}
	return ""
}

func (x *Data) GetEmbeddingApi() *EmbeddingAPI {
	if x != nil {
		return x.EmbeddingApi
	}
	return nil
}

type Auth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Issuer         string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	KeyVersion     string                 `protobuf:"bytes,2,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	PrivateKeyPath string                 `protobuf:"bytes,3,opt,name=private_key_path,json=privateKeyPath,proto3" json:"private_key_path,omitempty"`
	PublicKeyPath  string                 `protobuf:"bytes,4,opt,name=public_key_path,json=publicKeyPath,proto3" json:"public_key_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Auth) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Auth) GetKeyVersion() string {
	if x != nil {
		return x.KeyVersion
	}
	return ""
}

func (x *Auth) GetPrivateKeyPath() string {
	if x != nil {
		return x.PrivateKeyPath
	}
	return ""
}

func (x *Auth) GetPublicKeyPath() string {
	if x != nil {
		return x.PublicKeyPath
	}
	return ""
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"Q\n" +
	"\tBootstrap\x12$\n" +
	"\x06server\x18\x01 \x01(\v2\f.conf.ServerR\x06server\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".conf.DataR\x04data\"h\n" +
	"\x06Server\x12.\n" +
	"\x13connect_server_addr\x18\x01 \x01(\tR\x11connectServerAddr\x12.\n" +
	"\x13metrics_server_addr\x18\x02 \x01(\tR\x11metricsServerAddr\":\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"\x89\x01\n" +
	"\vServiceAddr\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x1c\n" +
	"\tinventory\x18\x02 \x01(\tR\tinventory\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x12\n" +
	"\x04auth\x18\x04 \x01(\tR\x04auth\x12\x18\n" +
	"\apayment\x18\x05 \x01(\tR\apayment\"c\n" +
	"\aPayment\x12*\n" +
	"\x11stripe_secret_key\x18\x01 \x01(\tR\x0fstripeSecretKey\x12,\n" +
	"\x12stripe_success_url\x18\x02 \x01(\tR\x10stripeSuccessUrl\"*\n" +
	"\x05Kafka\x12!\n" +
	"\fbroker_addrs\x18\x01 \x03(\tR\vbrokerAddrs\"{\n" +
	"\fEmbeddingAPI\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\fmax_distance\x18\x04 \x01(\x02R\vmaxDistance\"\xf7\x02\n" +
	"\x04Data\x12*\n" +
	"\bdatabase\x18\x01 \x01(\v2\x0e.conf.DatabaseR\bdatabase\x12!\n" +
	"\x05redis\x18\x02 \x01(\v2\v.conf.RedisR\x05redis\x124\n" +
	"\fservice_addr\x18\x03 \x01(\v2\x11.conf.ServiceAddrR\vserviceAddr\x12'\n" +
	"\apayment\x18\x04 \x01(\v2\r.conf.PaymentR\apayment\x12!\n" +
	"\x05kafka\x18\x05 \x01(\v2\v.conf.KafkaR\x05kafka\x12\x19\n" +
	"\bapp_name\x18\x06 \x01(\tR\aappName\x12\x1e\n" +
	"\x04auth\x18\a \x01(\v2\n" +
	".conf.AuthR\x04auth\x12*\n" +
	"\x11otlp_grpc_address\x18\b \x01(\tR\x0fotlpGrpcAddress\x127\n" +
	"\rembedding_api\x18\t \x01(\v2\x12.conf.EmbeddingAPIR\fembeddingApi\"\x91\x01\n" +
	"\x04Auth\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1f\n" +
	"\vkey_version\x18\x02 \x01(\tR\n" +
	"keyVersion\x12(\n" +
	"\x10private_key_path\x18\x03 \x01(\tR\x0eprivateKeyPath\x12&\n" +
	"\x0fpublic_key_path\x18\x04 \x01(\tR\rpublicKeyPathB,Z*github.com/azusayn/azushop/proto/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: conf.Bootstrap
	(*Server)(nil),              // 1: conf.Server
	(*Database)(nil),            // 2: conf.Database
	(*Redis)(nil),               // 3: conf.Redis
	(*ServiceAddr)(nil),         // 4: conf.ServiceAddr
	(*Payment)(nil),             // 5: conf.Payment
	(*Kafka)(nil),               // 6: conf.Kafka
	(*EmbeddingAPI)(nil),        // 7: conf.EmbeddingAPI
	(*Data)(nil),                // 8: conf.Data
	(*Auth)(nil),                // 9: conf.Auth
	(*durationpb.Duration)(nil), // 10: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: conf.Bootstrap.server:type_name -> conf.Server
	8,  // 1: conf.Bootstrap.data:type_name -> conf.Data
	10, // 2: conf.Redis.read_timeout:type_name -> google.protobuf.Duration
	10, // 3: conf.Redis.write_timeout:type_name -> google.protobuf.Duration
	2,  // 4: conf.Data.database:type_name -> conf.Database
	3,  // 5: conf.Data.redis:type_name -> conf.Redis
	4,  // 6: conf.Data.service_addr:type_name -> conf.ServiceAddr
	5,  // 7: conf.Data.payment:type_name -> conf.Payment
	6,  // 8: conf.Data.kafka:type_name -> conf.Kafka
	9,  // 9: conf.Data.auth:type_name -> conf.Auth
	7,  // 10: conf.Data.embedding_api:type_name -> conf.EmbeddingAPI
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
