syntax = "proto3";

package conf;

import "google/protobuf/duration.proto";

option go_package = "github.com/azusayn/azushop/proto/conf;conf";

message Bootstrap {
  Server server = 1;
  Data data = 2;
}

message Server {
  string connect_server_addr = 1;
  string metrics_server_addr = 2;
}

 message Database {
    string driver = 1;
    string source = 2;
  }
  message Redis {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration read_timeout = 3;
    google.protobuf.Duration write_timeout = 4;
  }
  message ServiceAddr {
    string product = 1;
    string inventory = 2;
    string order = 3;
    string auth = 4;
    string payment = 5;
  }
  message Payment {
    string stripe_secret_key = 1;
    string stripe_success_url = 2;
  }
  message Kafka {
    repeated string broker_addrs = 1;
  }

message EmbeddingAPI {
  string endpoint = 1;
  string secret = 2;
  string model = 3;
  float max_distance = 4;
}

message Data {
  Database database = 1;
  Redis redis = 2;
  ServiceAddr service_addr = 3;
  Payment payment = 4;
  Kafka kafka = 5;
  string app_name = 6;
  Auth auth = 7;
  string otlp_grpc_address = 8;
  EmbeddingAPI embedding_api = 9;
}

message Auth {
  string issuer = 1;
  string key_version = 2;
  string private_key_path = 3;
  string public_key_path = 4;
}