// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/order/v1/order.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/azusayn/azushop/proto/api/order/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrderServiceName is the fully-qualified name of the OrderService service.
	OrderServiceName = "order.v1.OrderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrderServiceCreateOrderProcedure is the fully-qualified name of the OrderService's CreateOrder
	// RPC.
	OrderServiceCreateOrderProcedure = "/order.v1.OrderService/CreateOrder"
	// OrderServiceCancelOrderProcedure is the fully-qualified name of the OrderService's CancelOrder
	// RPC.
	OrderServiceCancelOrderProcedure = "/order.v1.OrderService/CancelOrder"
	// OrderServiceListOrdersProcedure is the fully-qualified name of the OrderService's ListOrders RPC.
	OrderServiceListOrdersProcedure = "/order.v1.OrderService/ListOrders"
	// OrderServiceGetOrderProcedure is the fully-qualified name of the OrderService's GetOrder RPC.
	OrderServiceGetOrderProcedure = "/order.v1.OrderService/GetOrder"
)

// OrderServiceClient is a client for the order.v1.OrderService service.
type OrderServiceClient interface {
	// create order
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	// cancels order for given order ID.
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	// lists all orders owned by the customer.
	ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error)
	// retrieves the order for given order ID.
	GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.GetOrderResponse], error)
}

// NewOrderServiceClient constructs a client for the order.v1.OrderService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	orderServiceMethods := v1.File_api_order_v1_order_proto.Services().ByName("OrderService").Methods()
	return &orderServiceClient{
		createOrder: connect.NewClient[v1.CreateOrderRequest, v1.CreateOrderResponse](
			httpClient,
			baseURL+OrderServiceCreateOrderProcedure,
			connect.WithSchema(orderServiceMethods.ByName("CreateOrder")),
			connect.WithClientOptions(opts...),
		),
		cancelOrder: connect.NewClient[v1.CancelOrderRequest, v1.CancelOrderResponse](
			httpClient,
			baseURL+OrderServiceCancelOrderProcedure,
			connect.WithSchema(orderServiceMethods.ByName("CancelOrder")),
			connect.WithClientOptions(opts...),
		),
		listOrders: connect.NewClient[v1.ListOrdersRequest, v1.ListOrdersResponse](
			httpClient,
			baseURL+OrderServiceListOrdersProcedure,
			connect.WithSchema(orderServiceMethods.ByName("ListOrders")),
			connect.WithClientOptions(opts...),
		),
		getOrder: connect.NewClient[v1.GetOrderRequest, v1.GetOrderResponse](
			httpClient,
			baseURL+OrderServiceGetOrderProcedure,
			connect.WithSchema(orderServiceMethods.ByName("GetOrder")),
			connect.WithClientOptions(opts...),
		),
	}
}

// orderServiceClient implements OrderServiceClient.
type orderServiceClient struct {
	createOrder *connect.Client[v1.CreateOrderRequest, v1.CreateOrderResponse]
	cancelOrder *connect.Client[v1.CancelOrderRequest, v1.CancelOrderResponse]
	listOrders  *connect.Client[v1.ListOrdersRequest, v1.ListOrdersResponse]
	getOrder    *connect.Client[v1.GetOrderRequest, v1.GetOrderResponse]
}

// CreateOrder calls order.v1.OrderService.CreateOrder.
func (c *orderServiceClient) CreateOrder(ctx context.Context, req *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// CancelOrder calls order.v1.OrderService.CancelOrder.
func (c *orderServiceClient) CancelOrder(ctx context.Context, req *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return c.cancelOrder.CallUnary(ctx, req)
}

// ListOrders calls order.v1.OrderService.ListOrders.
func (c *orderServiceClient) ListOrders(ctx context.Context, req *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return c.listOrders.CallUnary(ctx, req)
}

// GetOrder calls order.v1.OrderService.GetOrder.
func (c *orderServiceClient) GetOrder(ctx context.Context, req *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.GetOrderResponse], error) {
	return c.getOrder.CallUnary(ctx, req)
}

// OrderServiceHandler is an implementation of the order.v1.OrderService service.
type OrderServiceHandler interface {
	// create order
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	// cancels order for given order ID.
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	// lists all orders owned by the customer.
	ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error)
	// retrieves the order for given order ID.
	GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.GetOrderResponse], error)
}

// NewOrderServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrderServiceHandler(svc OrderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orderServiceMethods := v1.File_api_order_v1_order_proto.Services().ByName("OrderService").Methods()
	orderServiceCreateOrderHandler := connect.NewUnaryHandler(
		OrderServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(orderServiceMethods.ByName("CreateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	orderServiceCancelOrderHandler := connect.NewUnaryHandler(
		OrderServiceCancelOrderProcedure,
		svc.CancelOrder,
		connect.WithSchema(orderServiceMethods.ByName("CancelOrder")),
		connect.WithHandlerOptions(opts...),
	)
	orderServiceListOrdersHandler := connect.NewUnaryHandler(
		OrderServiceListOrdersProcedure,
		svc.ListOrders,
		connect.WithSchema(orderServiceMethods.ByName("ListOrders")),
		connect.WithHandlerOptions(opts...),
	)
	orderServiceGetOrderHandler := connect.NewUnaryHandler(
		OrderServiceGetOrderProcedure,
		svc.GetOrder,
		connect.WithSchema(orderServiceMethods.ByName("GetOrder")),
		connect.WithHandlerOptions(opts...),
	)
	return "/order.v1.OrderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrderServiceCreateOrderProcedure:
			orderServiceCreateOrderHandler.ServeHTTP(w, r)
		case OrderServiceCancelOrderProcedure:
			orderServiceCancelOrderHandler.ServeHTTP(w, r)
		case OrderServiceListOrdersProcedure:
			orderServiceListOrdersHandler.ServeHTTP(w, r)
		case OrderServiceGetOrderProcedure:
			orderServiceGetOrderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrderServiceHandler struct{}

func (UnimplementedOrderServiceHandler) CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("order.v1.OrderService.CreateOrder is not implemented"))
}

func (UnimplementedOrderServiceHandler) CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("order.v1.OrderService.CancelOrder is not implemented"))
}

func (UnimplementedOrderServiceHandler) ListOrders(context.Context, *connect.Request[v1.ListOrdersRequest]) (*connect.Response[v1.ListOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("order.v1.OrderService.ListOrders is not implemented"))
}

func (UnimplementedOrderServiceHandler) GetOrder(context.Context, *connect.Request[v1.GetOrderRequest]) (*connect.Response[v1.GetOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("order.v1.OrderService.GetOrder is not implemented"))
}
