// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"azushop/internal/biz"
	"azushop/internal/conf"
	"azushop/internal/data"
	"azushop/internal/runner"
	"azushop/internal/server"
	"azushop/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo)
	authServiceService := service.NewAuthServiceService(userUsecase, dataData)
	productRepo := data.NewProductRepo(dataData)
	productUsecase := biz.NewProductUsecase(productRepo)
	productService := service.NewProductService(productUsecase)
	inventoryRepo := data.NewInventoryRepo(dataData)
	transaction := data.NewTransaction(dataData)
	inventoryUsecase := biz.NewInventoryUsecase(inventoryRepo, transaction)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	orderRepo := data.NewOrderRepo(dataData)
	orderUsecase := biz.NewOrderUsecase(orderRepo)
	orderService := service.NewOrderService(orderUsecase, dataData)
	paymentRepo := data.NewPaymentRepo(dataData)
	paymentPublisher := data.NewPaymentPublisher(dataData)
	paymentUsecase := biz.NewPaymentUsecase(paymentRepo, paymentPublisher)
	paymentService := service.NewPaymentService(paymentUsecase, dataData)
	grpcServer := server.NewGRPCServer(confServer, authServiceService, productService, inventoryService, orderService, paymentService, dataData, logger)
	httpServer := server.NewHTTPServer(confServer, authServiceService, logger)
	runnerManager := runner.NewRunnerManager(orderUsecase)
	app := newApp(logger, grpcServer, httpServer, runnerManager)
	return app, func() {
		cleanup()
	}, nil
}
