// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/product/v1/product.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/azusayn/azushop/proto/api/product/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProductServiceName is the fully-qualified name of the ProductService service.
	ProductServiceName = "product.v1.ProductService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProductServiceSearchProductsProcedure is the fully-qualified name of the ProductService's
	// SearchProducts RPC.
	ProductServiceSearchProductsProcedure = "/product.v1.ProductService/SearchProducts"
	// ProductServiceListSellerProductsProcedure is the fully-qualified name of the ProductService's
	// ListSellerProducts RPC.
	ProductServiceListSellerProductsProcedure = "/product.v1.ProductService/ListSellerProducts"
	// ProductServiceBatchCreateProductProcedure is the fully-qualified name of the ProductService's
	// BatchCreateProduct RPC.
	ProductServiceBatchCreateProductProcedure = "/product.v1.ProductService/BatchCreateProduct"
	// ProductServiceBatchUpdateProductProcedure is the fully-qualified name of the ProductService's
	// BatchUpdateProduct RPC.
	ProductServiceBatchUpdateProductProcedure = "/product.v1.ProductService/BatchUpdateProduct"
	// ProductServiceBatchGetSkusProcedure is the fully-qualified name of the ProductService's
	// BatchGetSkus RPC.
	ProductServiceBatchGetSkusProcedure = "/product.v1.ProductService/BatchGetSkus"
)

// ProductServiceClient is a client for the product.v1.ProductService service.
type ProductServiceClient interface {
	// SearchProducts searches for products by keyword.
	SearchProducts(context.Context, *connect.Request[v1.SearchProductsRequest]) (*connect.Response[v1.SearchProductsResponse], error)
	// retrieves product information for given seller_id and product status.
	ListSellerProducts(context.Context, *connect.Request[v1.ListSellerProductsRequest]) (*connect.Response[v1.ListSellerProductsResponse], error)
	// creates new products for given information.
	BatchCreateProduct(context.Context, *connect.Request[v1.BatchCreateProductRequest]) (*connect.Response[v1.BatchCreateProductResponse], error)
	// updates products' fields specified by the given update masks.
	BatchUpdateProduct(context.Context, *connect.Request[v1.BatchUpdateProductRequest]) (*connect.Response[v1.BatchUpdateProductResponse], error)
	// retrieves sku information for given skuIds.
	BatchGetSkus(context.Context, *connect.Request[v1.BatchGetSkusRequest]) (*connect.Response[v1.BatchGetSkusResponse], error)
}

// NewProductServiceClient constructs a client for the product.v1.ProductService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProductServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProductServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	productServiceMethods := v1.File_api_product_v1_product_proto.Services().ByName("ProductService").Methods()
	return &productServiceClient{
		searchProducts: connect.NewClient[v1.SearchProductsRequest, v1.SearchProductsResponse](
			httpClient,
			baseURL+ProductServiceSearchProductsProcedure,
			connect.WithSchema(productServiceMethods.ByName("SearchProducts")),
			connect.WithClientOptions(opts...),
		),
		listSellerProducts: connect.NewClient[v1.ListSellerProductsRequest, v1.ListSellerProductsResponse](
			httpClient,
			baseURL+ProductServiceListSellerProductsProcedure,
			connect.WithSchema(productServiceMethods.ByName("ListSellerProducts")),
			connect.WithClientOptions(opts...),
		),
		batchCreateProduct: connect.NewClient[v1.BatchCreateProductRequest, v1.BatchCreateProductResponse](
			httpClient,
			baseURL+ProductServiceBatchCreateProductProcedure,
			connect.WithSchema(productServiceMethods.ByName("BatchCreateProduct")),
			connect.WithClientOptions(opts...),
		),
		batchUpdateProduct: connect.NewClient[v1.BatchUpdateProductRequest, v1.BatchUpdateProductResponse](
			httpClient,
			baseURL+ProductServiceBatchUpdateProductProcedure,
			connect.WithSchema(productServiceMethods.ByName("BatchUpdateProduct")),
			connect.WithClientOptions(opts...),
		),
		batchGetSkus: connect.NewClient[v1.BatchGetSkusRequest, v1.BatchGetSkusResponse](
			httpClient,
			baseURL+ProductServiceBatchGetSkusProcedure,
			connect.WithSchema(productServiceMethods.ByName("BatchGetSkus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// productServiceClient implements ProductServiceClient.
type productServiceClient struct {
	searchProducts     *connect.Client[v1.SearchProductsRequest, v1.SearchProductsResponse]
	listSellerProducts *connect.Client[v1.ListSellerProductsRequest, v1.ListSellerProductsResponse]
	batchCreateProduct *connect.Client[v1.BatchCreateProductRequest, v1.BatchCreateProductResponse]
	batchUpdateProduct *connect.Client[v1.BatchUpdateProductRequest, v1.BatchUpdateProductResponse]
	batchGetSkus       *connect.Client[v1.BatchGetSkusRequest, v1.BatchGetSkusResponse]
}

// SearchProducts calls product.v1.ProductService.SearchProducts.
func (c *productServiceClient) SearchProducts(ctx context.Context, req *connect.Request[v1.SearchProductsRequest]) (*connect.Response[v1.SearchProductsResponse], error) {
	return c.searchProducts.CallUnary(ctx, req)
}

// ListSellerProducts calls product.v1.ProductService.ListSellerProducts.
func (c *productServiceClient) ListSellerProducts(ctx context.Context, req *connect.Request[v1.ListSellerProductsRequest]) (*connect.Response[v1.ListSellerProductsResponse], error) {
	return c.listSellerProducts.CallUnary(ctx, req)
}

// BatchCreateProduct calls product.v1.ProductService.BatchCreateProduct.
func (c *productServiceClient) BatchCreateProduct(ctx context.Context, req *connect.Request[v1.BatchCreateProductRequest]) (*connect.Response[v1.BatchCreateProductResponse], error) {
	return c.batchCreateProduct.CallUnary(ctx, req)
}

// BatchUpdateProduct calls product.v1.ProductService.BatchUpdateProduct.
func (c *productServiceClient) BatchUpdateProduct(ctx context.Context, req *connect.Request[v1.BatchUpdateProductRequest]) (*connect.Response[v1.BatchUpdateProductResponse], error) {
	return c.batchUpdateProduct.CallUnary(ctx, req)
}

// BatchGetSkus calls product.v1.ProductService.BatchGetSkus.
func (c *productServiceClient) BatchGetSkus(ctx context.Context, req *connect.Request[v1.BatchGetSkusRequest]) (*connect.Response[v1.BatchGetSkusResponse], error) {
	return c.batchGetSkus.CallUnary(ctx, req)
}

// ProductServiceHandler is an implementation of the product.v1.ProductService service.
type ProductServiceHandler interface {
	// SearchProducts searches for products by keyword.
	SearchProducts(context.Context, *connect.Request[v1.SearchProductsRequest]) (*connect.Response[v1.SearchProductsResponse], error)
	// retrieves product information for given seller_id and product status.
	ListSellerProducts(context.Context, *connect.Request[v1.ListSellerProductsRequest]) (*connect.Response[v1.ListSellerProductsResponse], error)
	// creates new products for given information.
	BatchCreateProduct(context.Context, *connect.Request[v1.BatchCreateProductRequest]) (*connect.Response[v1.BatchCreateProductResponse], error)
	// updates products' fields specified by the given update masks.
	BatchUpdateProduct(context.Context, *connect.Request[v1.BatchUpdateProductRequest]) (*connect.Response[v1.BatchUpdateProductResponse], error)
	// retrieves sku information for given skuIds.
	BatchGetSkus(context.Context, *connect.Request[v1.BatchGetSkusRequest]) (*connect.Response[v1.BatchGetSkusResponse], error)
}

// NewProductServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProductServiceHandler(svc ProductServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	productServiceMethods := v1.File_api_product_v1_product_proto.Services().ByName("ProductService").Methods()
	productServiceSearchProductsHandler := connect.NewUnaryHandler(
		ProductServiceSearchProductsProcedure,
		svc.SearchProducts,
		connect.WithSchema(productServiceMethods.ByName("SearchProducts")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceListSellerProductsHandler := connect.NewUnaryHandler(
		ProductServiceListSellerProductsProcedure,
		svc.ListSellerProducts,
		connect.WithSchema(productServiceMethods.ByName("ListSellerProducts")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceBatchCreateProductHandler := connect.NewUnaryHandler(
		ProductServiceBatchCreateProductProcedure,
		svc.BatchCreateProduct,
		connect.WithSchema(productServiceMethods.ByName("BatchCreateProduct")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceBatchUpdateProductHandler := connect.NewUnaryHandler(
		ProductServiceBatchUpdateProductProcedure,
		svc.BatchUpdateProduct,
		connect.WithSchema(productServiceMethods.ByName("BatchUpdateProduct")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceBatchGetSkusHandler := connect.NewUnaryHandler(
		ProductServiceBatchGetSkusProcedure,
		svc.BatchGetSkus,
		connect.WithSchema(productServiceMethods.ByName("BatchGetSkus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/product.v1.ProductService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProductServiceSearchProductsProcedure:
			productServiceSearchProductsHandler.ServeHTTP(w, r)
		case ProductServiceListSellerProductsProcedure:
			productServiceListSellerProductsHandler.ServeHTTP(w, r)
		case ProductServiceBatchCreateProductProcedure:
			productServiceBatchCreateProductHandler.ServeHTTP(w, r)
		case ProductServiceBatchUpdateProductProcedure:
			productServiceBatchUpdateProductHandler.ServeHTTP(w, r)
		case ProductServiceBatchGetSkusProcedure:
			productServiceBatchGetSkusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProductServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProductServiceHandler struct{}

func (UnimplementedProductServiceHandler) SearchProducts(context.Context, *connect.Request[v1.SearchProductsRequest]) (*connect.Response[v1.SearchProductsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product.v1.ProductService.SearchProducts is not implemented"))
}

func (UnimplementedProductServiceHandler) ListSellerProducts(context.Context, *connect.Request[v1.ListSellerProductsRequest]) (*connect.Response[v1.ListSellerProductsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product.v1.ProductService.ListSellerProducts is not implemented"))
}

func (UnimplementedProductServiceHandler) BatchCreateProduct(context.Context, *connect.Request[v1.BatchCreateProductRequest]) (*connect.Response[v1.BatchCreateProductResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product.v1.ProductService.BatchCreateProduct is not implemented"))
}

func (UnimplementedProductServiceHandler) BatchUpdateProduct(context.Context, *connect.Request[v1.BatchUpdateProductRequest]) (*connect.Response[v1.BatchUpdateProductResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product.v1.ProductService.BatchUpdateProduct is not implemented"))
}

func (UnimplementedProductServiceHandler) BatchGetSkus(context.Context, *connect.Request[v1.BatchGetSkusRequest]) (*connect.Response[v1.BatchGetSkusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product.v1.ProductService.BatchGetSkus is not implemented"))
}
