// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/azusayn/azushop/internal/biz"
	"github.com/azusayn/azushop/internal/data"
	"github.com/azusayn/azushop/internal/pkg/telemetry"
	"github.com/azusayn/azushop/internal/server"
	"github.com/azusayn/azushop/internal/service"
	"github.com/azusayn/azushop/proto/conf"
	"github.com/google/wire"
)

// Injectors from wire.go:

func wireApp(cd *conf.Data, cs *conf.Server) (*App, func(), error) {
	postgres, err := data.NewPostgres(cd)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(postgres)
	userUsecase := biz.NewUserUsecase(userRepo)
	authService, err := service.NewAuthService(userUsecase, cd)
	if err != nil {
		return nil, nil, err
	}
	authServiceConnectHandler := service.NewAuthServiceConnectHandler(authService)
	textMapPropagator := telemetry.NewTextMapPropagator()
	connectServerConfig, err := newConnectServerConfig(authServiceConnectHandler, cs, textMapPropagator)
	if err != nil {
		return nil, nil, err
	}
	connectServer := server.NewConnectServer(connectServerConfig)
	metricsServer := server.NewMetricsServer(cs)
	app := newApp(connectServer, metricsServer)
	return app, func() {
	}, nil
}

// wire.go:

var wireProviders = wire.NewSet(telemetry.NewTextMapPropagator, data.AuthDataProviderSet, biz.NewUserUsecase, service.NewAuthService, service.NewAuthServiceConnectHandler, newConnectServerConfig, server.NewConnectServer, server.NewMetricsServer, newApp)
