server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  app_name: "azushop.auth"
  database:
    driver: pgx
    source: postgres://postgres:270153@192.168.68.163:5432/postgres?sslmode=disable
  auth:
    issuer: azushop
    private_key_path: "./misc/secret/dev.private.pem"
