server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  app_name: "azushop"
  database:
    driver: pgx
    source: postgres://postgres:270153@127.0.0.1:5432/postgres?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  payment:
    stripe_secret_key:
    stripe_success_url:
  kafka:
    broker_addrs:
      - "192.168.1.6:9092"
