server:
  http:
    addr: 0.0.0.0:8002
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  app_name: "azushop.inventory"
  database:
    driver: pgx
    source: postgres://postgres:270153@localhost:5432/postgres?sslmode=disable
  kafka:
    broker_addrs:
      - "localhost:9092"
auth:
  issuer: azushop
  public_key_path: "./misc/secret/dev.public.pem"
