server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  app_name: "azushop.inventory"
  database:
    driver: pgx
    source: postgres://postgres:270153@192.168.68.163:5432/postgres?sslmode=disable
  kafka:
    broker_addrs:
      - "192.168.68.163:9092"
auth:
  issuer: azushop
  public_key_path: "./misc/secret/dev.public.pem"
