server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s
data:
  app_name: "azushop.payment"
  database:
    driver: pgx
    source: postgres://postgres:270153@localhost:5432/postgres?sslmode=disable
  redis:
    addr: localhost:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  service_addr:
    order: 127.0.0.1:9003
  payment:
    stripe_secret_key:
    stripe_success_url: https://4c55-240e-3b5-caf-b6e0-58ab-d467-b363-d0a.ngrok-free.app/v1/payment/callback/stripe
  kafka:
    broker_addrs:
      - "localhost:9092"
  auth:
    issuer: azushop
    public_key_path: "./misc/secret/dev.public.pem"
