server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  app_name: "azushop.product"
  database:
    driver: pgx
    source: postgres://postgres:270153@192.168.68.163:5432/postgres?sslmode=disable
  redis:
    addr: 192.168.68.163:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    broker_addrs:
      - "192.168.68.163:9092"
  auth:
    issuer: azushop
    public_key_path: "./misc/secret/dev.public.pem"
