// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.5
// source: api/payment/v1/payment.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPaymentServiceCallback = "/payment.v1.PaymentService/Callback"

type PaymentServiceHTTPServer interface {
	// Callback callback API for external payment providers.
	// currently only support stripe as the provider.
	Callback(context.Context, *CallbackRequest) (*CallbackResponse, error)
}

func RegisterPaymentServiceHTTPServer(s *http.Server, srv PaymentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/payment/callback/{provider}", _PaymentService_Callback0_HTTP_Handler(srv))
}

func _PaymentService_Callback0_HTTP_Handler(srv PaymentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CallbackRequest
		if err := ctx.Bind(&in.Raw); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPaymentServiceCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Callback(ctx, req.(*CallbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CallbackResponse)
		return ctx.Result(200, reply)
	}
}

type PaymentServiceHTTPClient interface {
	// Callback callback API for external payment providers.
	// currently only support stripe as the provider.
	Callback(ctx context.Context, req *CallbackRequest, opts ...http.CallOption) (rsp *CallbackResponse, err error)
}

type PaymentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPaymentServiceHTTPClient(client *http.Client) PaymentServiceHTTPClient {
	return &PaymentServiceHTTPClientImpl{client}
}

// Callback callback API for external payment providers.
// currently only support stripe as the provider.
func (c *PaymentServiceHTTPClientImpl) Callback(ctx context.Context, in *CallbackRequest, opts ...http.CallOption) (*CallbackResponse, error) {
	var out CallbackResponse
	pattern := "/v1/payment/callback/{provider}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPaymentServiceCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Raw, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
