server:
  connect_server_addr: 0.0.0.0:{{ .Values.services.service.targetPort }}
  metrics_server_addr: 0.0.0.0:9090
data:
  app_name: "azushop.inventory"
  database:
    driver: pgx
    source: postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Values.postgres.service.name }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}?sslmode=disable
  kafka:
    broker_addrs:
{{- range .Values.serviceConfig.kafka.brokerAddrs }}
      - {{ . | quote }}
{{- end }}
  auth:
    issuer: {{ .Values.serviceConfig.auth.issuer | quote }}
    public_key_path: {{ .Values.serviceConfig.auth.publicKeyPath | quote }}
  otlp_grpc_address: {{ .Values.serviceConfig.otlpGrpcAddress | quote }}
