server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
data:
  app_name: "azushop.inventory"
  database:
    driver: pgx
    source: postgres://postgres:270153@postgres:5432/postgres?sslmode=disable
  kafka:
    broker_addrs:
      - "kafka-service:9092"
  auth:
    issuer: azushop
    public_key_path: "configs/dev.public.pem"
  otlp_grpc_address: "otel-collector:4317"
