server:
  http:
    addr: 0.0.0.0:{{ .Values.services.service.targetPort }}
    timeout: 1s
data:
  app_name: "azushop.order"
  database:
    driver: pgx
    source: postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Values.postgres.service.name }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}?sslmode=disable
  redis:
    addr: {{ .Values.serviceConfig.redis.addr | quote }}
    read_timeout: {{ .Values.serviceConfig.redis.readTimeout | quote }}
    write_timeout: {{ .Values.serviceConfig.redis.writeTimeout | quote }}
  service_addr:
    product: {{ .Values.serviceConfig.serviceAddr.product | quote }}
    inventory: {{ .Values.serviceConfig.serviceAddr.inventory | quote }}
  payment:
    stripe_secret_key:
    stripe_success_url:
  kafka:
    broker_addrs:
{{- range .Values.serviceConfig.kafka.brokerAddrs }}
      - {{ . | quote }}
{{- end }}
  auth:
    issuer: {{ .Values.serviceConfig.auth.issuer | quote }}
    public_key_path: {{ .Values.serviceConfig.auth.publicKeyPath | quote }}
  otlp_grpc_address: {{ .Values.serviceConfig.otlpGrpcAddress | quote }}
