// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/inventory/v1/inventory.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/azusayn/azushop/proto/api/inventory/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InventoryServiceName is the fully-qualified name of the InventoryService service.
	InventoryServiceName = "inventory.v1.InventoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InventoryServiceAdjustStockProcedure is the fully-qualified name of the InventoryService's
	// AdjustStock RPC.
	InventoryServiceAdjustStockProcedure = "/inventory.v1.InventoryService/AdjustStock"
	// InventoryServiceBatchGetStockProcedure is the fully-qualified name of the InventoryService's
	// BatchGetStock RPC.
	InventoryServiceBatchGetStockProcedure = "/inventory.v1.InventoryService/BatchGetStock"
	// InventoryServiceReleaseStockProcedure is the fully-qualified name of the InventoryService's
	// ReleaseStock RPC.
	InventoryServiceReleaseStockProcedure = "/inventory.v1.InventoryService/ReleaseStock"
)

// InventoryServiceClient is a client for the inventory.v1.InventoryService service.
type InventoryServiceClient interface {
	// interfaces used by merchants and administrators.
	// sets stock to a specific quantity.
	AdjustStock(context.Context, *connect.Request[v1.AdjustStockRequest]) (*connect.Response[v1.AdjustStockResponse], error)
	// retrieves SKU information for given SKU IDs.
	BatchGetStock(context.Context, *connect.Request[v1.BatchGetStockRequest]) (*connect.Response[v1.BatchGetStockResponse], error)
	// interfaces used by internal services.
	// release reserved stock when a customer cancels an order.
	ReleaseStock(context.Context, *connect.Request[v1.ReleaseStockRequest]) (*connect.Response[v1.ReleaseStockResponse], error)
}

// NewInventoryServiceClient constructs a client for the inventory.v1.InventoryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInventoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InventoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inventoryServiceMethods := v1.File_api_inventory_v1_inventory_proto.Services().ByName("InventoryService").Methods()
	return &inventoryServiceClient{
		adjustStock: connect.NewClient[v1.AdjustStockRequest, v1.AdjustStockResponse](
			httpClient,
			baseURL+InventoryServiceAdjustStockProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("AdjustStock")),
			connect.WithClientOptions(opts...),
		),
		batchGetStock: connect.NewClient[v1.BatchGetStockRequest, v1.BatchGetStockResponse](
			httpClient,
			baseURL+InventoryServiceBatchGetStockProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("BatchGetStock")),
			connect.WithClientOptions(opts...),
		),
		releaseStock: connect.NewClient[v1.ReleaseStockRequest, v1.ReleaseStockResponse](
			httpClient,
			baseURL+InventoryServiceReleaseStockProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ReleaseStock")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inventoryServiceClient implements InventoryServiceClient.
type inventoryServiceClient struct {
	adjustStock   *connect.Client[v1.AdjustStockRequest, v1.AdjustStockResponse]
	batchGetStock *connect.Client[v1.BatchGetStockRequest, v1.BatchGetStockResponse]
	releaseStock  *connect.Client[v1.ReleaseStockRequest, v1.ReleaseStockResponse]
}

// AdjustStock calls inventory.v1.InventoryService.AdjustStock.
func (c *inventoryServiceClient) AdjustStock(ctx context.Context, req *connect.Request[v1.AdjustStockRequest]) (*connect.Response[v1.AdjustStockResponse], error) {
	return c.adjustStock.CallUnary(ctx, req)
}

// BatchGetStock calls inventory.v1.InventoryService.BatchGetStock.
func (c *inventoryServiceClient) BatchGetStock(ctx context.Context, req *connect.Request[v1.BatchGetStockRequest]) (*connect.Response[v1.BatchGetStockResponse], error) {
	return c.batchGetStock.CallUnary(ctx, req)
}

// ReleaseStock calls inventory.v1.InventoryService.ReleaseStock.
func (c *inventoryServiceClient) ReleaseStock(ctx context.Context, req *connect.Request[v1.ReleaseStockRequest]) (*connect.Response[v1.ReleaseStockResponse], error) {
	return c.releaseStock.CallUnary(ctx, req)
}

// InventoryServiceHandler is an implementation of the inventory.v1.InventoryService service.
type InventoryServiceHandler interface {
	// interfaces used by merchants and administrators.
	// sets stock to a specific quantity.
	AdjustStock(context.Context, *connect.Request[v1.AdjustStockRequest]) (*connect.Response[v1.AdjustStockResponse], error)
	// retrieves SKU information for given SKU IDs.
	BatchGetStock(context.Context, *connect.Request[v1.BatchGetStockRequest]) (*connect.Response[v1.BatchGetStockResponse], error)
	// interfaces used by internal services.
	// release reserved stock when a customer cancels an order.
	ReleaseStock(context.Context, *connect.Request[v1.ReleaseStockRequest]) (*connect.Response[v1.ReleaseStockResponse], error)
}

// NewInventoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInventoryServiceHandler(svc InventoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inventoryServiceMethods := v1.File_api_inventory_v1_inventory_proto.Services().ByName("InventoryService").Methods()
	inventoryServiceAdjustStockHandler := connect.NewUnaryHandler(
		InventoryServiceAdjustStockProcedure,
		svc.AdjustStock,
		connect.WithSchema(inventoryServiceMethods.ByName("AdjustStock")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceBatchGetStockHandler := connect.NewUnaryHandler(
		InventoryServiceBatchGetStockProcedure,
		svc.BatchGetStock,
		connect.WithSchema(inventoryServiceMethods.ByName("BatchGetStock")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceReleaseStockHandler := connect.NewUnaryHandler(
		InventoryServiceReleaseStockProcedure,
		svc.ReleaseStock,
		connect.WithSchema(inventoryServiceMethods.ByName("ReleaseStock")),
		connect.WithHandlerOptions(opts...),
	)
	return "/inventory.v1.InventoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InventoryServiceAdjustStockProcedure:
			inventoryServiceAdjustStockHandler.ServeHTTP(w, r)
		case InventoryServiceBatchGetStockProcedure:
			inventoryServiceBatchGetStockHandler.ServeHTTP(w, r)
		case InventoryServiceReleaseStockProcedure:
			inventoryServiceReleaseStockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInventoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInventoryServiceHandler struct{}

func (UnimplementedInventoryServiceHandler) AdjustStock(context.Context, *connect.Request[v1.AdjustStockRequest]) (*connect.Response[v1.AdjustStockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory.v1.InventoryService.AdjustStock is not implemented"))
}

func (UnimplementedInventoryServiceHandler) BatchGetStock(context.Context, *connect.Request[v1.BatchGetStockRequest]) (*connect.Response[v1.BatchGetStockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory.v1.InventoryService.BatchGetStock is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ReleaseStock(context.Context, *connect.Request[v1.ReleaseStockRequest]) (*connect.Response[v1.ReleaseStockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory.v1.InventoryService.ReleaseStock is not implemented"))
}
